# Generated by Django 3.2.6 on 2021-08-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogcomment_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
    ]
