# Generated by Django 3.2.6 on 2021-08-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_blogcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
