# Generated by Django 3.2.6 on 2021-08-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_blogcomment_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userform',
            old_name='number',
            new_name='phonenumber',
        ),
        migrations.AddField(
            model_name='userform',
            name='Class',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
