# Generated by Django 3.2.6 on 2021-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210812_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='image',
            field=models.ImageField(blank=True, upload_to='upload/images'),
        ),
    ]
