# Generated by Django 3.2.6 on 2021-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_blogcomment_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100)),
                ('program_name', models.CharField(max_length=100)),
                ('program_date', models.DateTimeField()),
                ('program_venue', models.CharField(max_length=100)),
                ('program_audience', models.CharField(max_length=100)),
                ('program_details', models.TextField()),
                ('program_image', models.ImageField(blank=True, upload_to='upload/images')),
            ],
        ),
    ]
